// Generated by CoffeeScript 1.6.3
(function(window, document) {
  var _cordova;
  _cordova = (function() {
    function _cordova() {}

    _cordova.prototype.construstor = function() {
      var _this;
      _this = this;
      this.prototype = {
        evt: function() {}
      };
      return this;
    };

    return _cordova;

  })();
  return window.cordova = function(callback) {
    if (typeof callback !== 'function') {
      throw new Error('cordova(param) required and must be function');
    }
    return document.addEventListener("deviceready", callback(new _cordova()), false);
  };
})(window, document);
